/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as limitsModuleSol from "./LimitsModule.sol";
export { SocialRecoveryModule__factory } from "./SocialRecoveryModule__factory";
