/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as communityContracts from "./community-contracts";
export type { communityContracts };
import type * as contracts from "./contracts";
export type { contracts };
