/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IERC7579Module,
  IERC7579ModuleInterface,
} from "../../../../../@openzeppelin/contracts/interfaces/draft-IERC7579.sol/IERC7579Module";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "moduleTypeId",
        type: "uint256",
      },
    ],
    name: "isModuleType",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onInstall",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onUninstall",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IERC7579Module__factory {
  static readonly abi = _abi;
  static createInterface(): IERC7579ModuleInterface {
    return new Interface(_abi) as IERC7579ModuleInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IERC7579Module {
    return new Contract(address, _abi, runner) as unknown as IERC7579Module;
  }
}
