/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IEntryPointNonces,
  IEntryPointNoncesInterface,
} from "../../../../../@openzeppelin/contracts/interfaces/draft-IERC4337.sol/IEntryPointNonces";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "uint192",
        name: "key",
        type: "uint192",
      },
    ],
    name: "getNonce",
    outputs: [
      {
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IEntryPointNonces__factory {
  static readonly abi = _abi;
  static createInterface(): IEntryPointNoncesInterface {
    return new Interface(_abi) as IEntryPointNoncesInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IEntryPointNonces {
    return new Contract(address, _abi, runner) as unknown as IEntryPointNonces;
  }
}
