/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as limitsModuleSol from "./LimitsModule.sol";
export type { limitsModuleSol };
export type { SocialRecoveryModule } from "./SocialRecoveryModule";
