/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
} from "../../../../../common";

export interface ERC7579UtilsInterface extends Interface {
  getEvent(nameOrSignatureOrTopic: "ERC7579TryExecuteFail"): EventFragment;
}

export namespace ERC7579TryExecuteFailEvent {
  export type InputTuple = [
    batchExecutionIndex: BigNumberish,
    returndata: BytesLike
  ];
  export type OutputTuple = [batchExecutionIndex: bigint, returndata: string];
  export interface OutputObject {
    batchExecutionIndex: bigint;
    returndata: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ERC7579Utils extends BaseContract {
  connect(runner?: ContractRunner | null): ERC7579Utils;
  waitForDeployment(): Promise<this>;

  interface: ERC7579UtilsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getEvent(
    key: "ERC7579TryExecuteFail"
  ): TypedContractEvent<
    ERC7579TryExecuteFailEvent.InputTuple,
    ERC7579TryExecuteFailEvent.OutputTuple,
    ERC7579TryExecuteFailEvent.OutputObject
  >;

  filters: {
    "ERC7579TryExecuteFail(uint256,bytes)": TypedContractEvent<
      ERC7579TryExecuteFailEvent.InputTuple,
      ERC7579TryExecuteFailEvent.OutputTuple,
      ERC7579TryExecuteFailEvent.OutputObject
    >;
    ERC7579TryExecuteFail: TypedContractEvent<
      ERC7579TryExecuteFailEvent.InputTuple,
      ERC7579TryExecuteFailEvent.OutputTuple,
      ERC7579TryExecuteFailEvent.OutputObject
    >;
  };
}
